---
- name: Set up jenkins slave machines
  hosts: jenkins-slaves
  remote_user: ansible
  vars:
    - remote_root_directory: /home/jenkins/jenkins_slave
  become: yes
  roles:
    - jenkins-slave-setup
